apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: card-scheduling
  name: card-scheduling
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: card-scheduling
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: card-scheduling
    spec:
      containers:
        - image: notjohn/card-scheduling-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: card-scheduling-service
          envFrom:
            - configMapRef:
                name: card-scheduling
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: card-scheduling
  name: card-scheduling
  namespace: default
spec:
  ports:
    - port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    app: card-scheduling
  sessionAffinity: None
  type: LoadBalancer


---

apiVersion: v1
data:
  LEARNER_URI: http://learner
  CARD_URI: http://card
kind: ConfigMap
metadata:
  name: card-scheduling
  namespace: default