apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: teacher-ui
  name: teacher-ui
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teacher-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: teacher-ui
    spec:
      containers:
        - image: notjohn/teacher-ui:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: teacher-ui
          envFrom:
            - configMapRef:
                name: teacher-ui
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: teacher-ui
  name: teacher-ui
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: teacher-ui
  sessionAffinity: None
  type: LoadBalancer


---

apiVersion: v1
data:
  LEARNER_URI: http://learner
  CARD_URI: http://card
  CARD_SCHEDULING_URI: http://card-scheduling
kind: ConfigMap
metadata:
  name: teacher-ui
  namespace: default