server.port: 8000

logging:
  level:
    org:
      springframework:
        jdbc.datasource.init.ScriptUtils: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
#    defer-datasource-initialization: true
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default

#
#  spring.datasource.url=jdbc:h2:mem:testdb;NON_KEYWORDS=USER
#  spring.h2.console.enabled=true
#  spring.jpa.defer-datasource-initialization=true
#  spring.data.jpa.repositories.bootstrap-mode=default
