apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: card
  name: card
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: card
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
        - image: notjohn/card-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: card-service
      #          envFrom:
      #            - configMapRef:
      #                name: card
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: card
  name: card
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: card
  sessionAffinity: None
  type: LoadBalancer
