apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: learner
  name: learner
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: learner
    spec:
      containers:
        - image: notjohn/learner-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: learner-service
#          envFrom:
#            - configMapRef:
#                name: learner
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: learner
  name: learner
  namespace: default
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: learner
  sessionAffinity: None
  type: LoadBalancer

