
server.port: 8100



#logging:
#  level:
#    org:
#      springframework:
#        jdbc.datasource.init.ScriptUtils: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default


